/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.nasa.hq.dogshop.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import gov.nasa.hq.dogshop.model.Leash;
import gov.nasa.hq.dogshop.model.LeashModel;
import gov.nasa.hq.dogshop.model.LeashSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Leash service. Represents a row in the &quot;nasa_Leash&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LeashModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeashImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeashImpl
 * @see Leash
 * @see LeashModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LeashModelImpl extends BaseModelImpl<Leash> implements LeashModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leash model instance should use the {@link Leash} interface instead.
	 */
	public static final String TABLE_NAME = "nasa_Leash";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "leashId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "material", Types.VARCHAR },
			{ "color", Types.VARCHAR },
			{ "length", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leashId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("material", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("color", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("length", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table nasa_Leash (uuid_ VARCHAR(75) null,leashId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,material VARCHAR(75) null,color VARCHAR(75) null,length INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table nasa_Leash";
	public static final String ORDER_BY_JPQL = " ORDER BY leash.material ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nasa_Leash.material ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(gov.nasa.hq.dogshop.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.gov.nasa.hq.dogshop.model.Leash"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(gov.nasa.hq.dogshop.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.gov.nasa.hq.dogshop.model.Leash"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(gov.nasa.hq.dogshop.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.gov.nasa.hq.dogshop.model.Leash"),
			true);
	public static final long COLOR_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long MATERIAL_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Leash toModel(LeashSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Leash model = new LeashImpl();

		model.setUuid(soapModel.getUuid());
		model.setLeashId(soapModel.getLeashId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMaterial(soapModel.getMaterial());
		model.setColor(soapModel.getColor());
		model.setLength(soapModel.getLength());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Leash> toModels(LeashSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Leash> models = new ArrayList<Leash>(soapModels.length);

		for (LeashSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(gov.nasa.hq.dogshop.service.util.ServiceProps.get(
				"lock.expiration.time.gov.nasa.hq.dogshop.model.Leash"));

	public LeashModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leashId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeashId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leashId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Leash.class;
	}

	@Override
	public String getModelClassName() {
		return Leash.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("leashId", getLeashId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("material", getMaterial());
		attributes.put("color", getColor());
		attributes.put("length", getLength());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long leashId = (Long)attributes.get("leashId");

		if (leashId != null) {
			setLeashId(leashId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String material = (String)attributes.get("material");

		if (material != null) {
			setMaterial(material);
		}

		String color = (String)attributes.get("color");

		if (color != null) {
			setColor(color);
		}

		Integer length = (Integer)attributes.get("length");

		if (length != null) {
			setLength(length);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLeashId() {
		return _leashId;
	}

	@Override
	public void setLeashId(long leashId) {
		_leashId = leashId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMaterial() {
		if (_material == null) {
			return StringPool.BLANK;
		}
		else {
			return _material;
		}
	}

	@Override
	public void setMaterial(String material) {
		_columnBitmask = -1L;

		_material = material;
	}

	@JSON
	@Override
	public String getColor() {
		if (_color == null) {
			return StringPool.BLANK;
		}
		else {
			return _color;
		}
	}

	@Override
	public void setColor(String color) {
		_columnBitmask |= COLOR_COLUMN_BITMASK;

		if (_originalColor == null) {
			_originalColor = _color;
		}

		_color = color;
	}

	public String getOriginalColor() {
		return GetterUtil.getString(_originalColor);
	}

	@JSON
	@Override
	public int getLength() {
		return _length;
	}

	@Override
	public void setLength(int length) {
		_length = length;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Leash.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Leash.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Leash toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Leash)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeashImpl leashImpl = new LeashImpl();

		leashImpl.setUuid(getUuid());
		leashImpl.setLeashId(getLeashId());
		leashImpl.setGroupId(getGroupId());
		leashImpl.setCompanyId(getCompanyId());
		leashImpl.setUserId(getUserId());
		leashImpl.setUserName(getUserName());
		leashImpl.setCreateDate(getCreateDate());
		leashImpl.setModifiedDate(getModifiedDate());
		leashImpl.setMaterial(getMaterial());
		leashImpl.setColor(getColor());
		leashImpl.setLength(getLength());

		leashImpl.resetOriginalValues();

		return leashImpl;
	}

	@Override
	public int compareTo(Leash leash) {
		int value = 0;

		value = getMaterial().compareTo(leash.getMaterial());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Leash)) {
			return false;
		}

		Leash leash = (Leash)obj;

		long primaryKey = leash.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LeashModelImpl leashModelImpl = this;

		leashModelImpl._originalUuid = leashModelImpl._uuid;

		leashModelImpl._originalGroupId = leashModelImpl._groupId;

		leashModelImpl._setOriginalGroupId = false;

		leashModelImpl._originalCompanyId = leashModelImpl._companyId;

		leashModelImpl._setOriginalCompanyId = false;

		leashModelImpl._setModifiedDate = false;

		leashModelImpl._originalColor = leashModelImpl._color;

		leashModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Leash> toCacheModel() {
		LeashCacheModel leashCacheModel = new LeashCacheModel();

		leashCacheModel.uuid = getUuid();

		String uuid = leashCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leashCacheModel.uuid = null;
		}

		leashCacheModel.leashId = getLeashId();

		leashCacheModel.groupId = getGroupId();

		leashCacheModel.companyId = getCompanyId();

		leashCacheModel.userId = getUserId();

		leashCacheModel.userName = getUserName();

		String userName = leashCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			leashCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			leashCacheModel.createDate = createDate.getTime();
		}
		else {
			leashCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leashCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leashCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leashCacheModel.material = getMaterial();

		String material = leashCacheModel.material;

		if ((material != null) && (material.length() == 0)) {
			leashCacheModel.material = null;
		}

		leashCacheModel.color = getColor();

		String color = leashCacheModel.color;

		if ((color != null) && (color.length() == 0)) {
			leashCacheModel.color = null;
		}

		leashCacheModel.length = getLength();

		return leashCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", leashId=");
		sb.append(getLeashId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", material=");
		sb.append(getMaterial());
		sb.append(", color=");
		sb.append(getColor());
		sb.append(", length=");
		sb.append(getLength());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("gov.nasa.hq.dogshop.model.Leash");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leashId</column-name><column-value><![CDATA[");
		sb.append(getLeashId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>material</column-name><column-value><![CDATA[");
		sb.append(getMaterial());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>color</column-name><column-value><![CDATA[");
		sb.append(getColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>length</column-name><column-value><![CDATA[");
		sb.append(getLength());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Leash.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Leash.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _leashId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _material;
	private String _color;
	private String _originalColor;
	private int _length;
	private long _columnBitmask;
	private Leash _escapedModel;
}