/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.nasa.hq.dogshop.model.impl;

import aQute.bnd.annotation.ProviderType;

import gov.nasa.hq.dogshop.model.Leash;
import gov.nasa.hq.dogshop.service.LeashLocalServiceUtil;

/**
 * The extended model base implementation for the Leash service. Represents a row in the &quot;nasa_Leash&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeashImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeashImpl
 * @see Leash
 * @generated
 */
@ProviderType
public abstract class LeashBaseImpl extends LeashModelImpl implements Leash {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leash model instance should use the {@link Leash} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LeashLocalServiceUtil.addLeash(this);
		}
		else {
			LeashLocalServiceUtil.updateLeash(this);
		}
	}
}